<x-layout>
    @include('home.component.main.main')
    @include('home.component.aboutUs.aboutUs')
    @include('home.component.services.services')
    @include('home.component.values.values')
    @include('home.component.staff.staff')
    @include('home.component.signUp.signUp')
    @include('home.component.reviews.reviews')
</x-layout>